export type EventType = "convention" | "showcase" | "awards" | "esports" | "sale";

export interface GamingEvent {
  id: string;
  name: string;
  type: EventType;
  startDate: string; // YYYY-MM-DD
  endDate: string;   // YYYY-MM-DD
  location?: string;
  description: string;
  url?: string;
  color: string;
  logoUrl?: string;  // Official banner/og:image for popover header
}

const PAX_EAST_BANNER = "https://east.paxsite.com/content/dam/sitebuilder/rna/pax/east/2024/images/framework/pax-east-gradient-left-right-73171a-to-D9272D.jpg/_jcr_content/renditions/original.image_file.375.375.file/984193481/pax-east-gradient-left-right-73171a-to-D9272D.jpg";
const PAX_WEST_BANNER = "https://west.paxsite.com/content/dam/sitebuilder/rna/pax/west/metadata/seo/heros/hero-miscellaneous-pax-west.png/_jcr_content/renditions/original./031809964/hero-miscellaneous-pax-west.png";
const PAX_AUS_BANNER  = "https://aus.paxsite.com/content/dam/sitebuilder/rxau/pax/aus/branding/us-placeholders/aus-placeholder.png/_jcr_content/renditions/original.image_file.1919.960.file/290877126/aus-placeholder.png";
const SGF_BANNER      = "https://cdn.prod.website-files.com/65f20ae26ba45240543579bc/67fd991dca5be10f868c4971_load_image_desktop_v5.webp";
const SDCC_BANNER     = "https://comic-con-prod-uploads.s3.amazonaws.com/uploads/sites/4/2023/09/cc-hero-1024x679.jpg";
const BGS_BANNER      = "https://www.brasilgameshow.com.br/wp-content/themes/newsitebgs/images/slogan2026v4.webp";
const GSTAR_BANNER    = "https://www.gstar.or.kr/img/img_exhibition.png";
const TGS_TW_BANNER   = "https://tgs.tca.org.tw/images/banner/_1767319692.jpg";
const EWC_BANNER      = "https://d3h9qea4qy4169.cloudfront.net/887a601e_7716_4974_bccb_509d4016e2be_1f3cd47ecc.jpg";
const MEFCC_BANNER    = "https://knect365.imgix.net/uploads/MEFCC-Abu-Dhabi-Logo-White-49b99c7858082d50bff4e3d25e41027a.png?auto=format&fit=max&w=800";
const GAMESCOM_BANNER = "https://eu-central-1-gamescom.graphassets.com/AMwDHZTUSMaIlRlMFLL7Qz/PssD8VBzTXq72TP0ISkN";
const ONL_BANNER      = "https://eu-central-1-gamescom.graphassets.com/AMwDHZTUSMaIlRlMFLL7Qz/cmehi4nva0h9g07w4fdvuvwnp";
const GDC_BANNER      = "https://knect365.imgix.net/uploads/GDC-white-a7871e2b774f7ecda4ee930bd43649c8.png?auto=format&fit=max&w=800";
const TGA_BANNER      = "https://cdn.thegameawards.com/frontend/jpegs/2026-Share-Banner.jpg";
const GJA_BANNER      = "https://assets.swoogo.com/uploads/medium/5147707-67ec194eeb105.png";
const XBOX_SCH_BANNER = "https://xboxwire.thesourcemediaassets.com/sites/2/2025/06/2025_FINAL_RGB_16x9_HERO-164d81ba2776e8915ffd.jpg";
const TGS_BANNER      = "https://tgs.cesa.or.jp/images/meta/ogp.png";
const DICE_BANNER     = "https://www.interactive.org/images/layout/academy-of-interactive-arts-and-sciences-logo-lg.png";
const IGDC_BANNER     = "https://indiagdc.com/wp-content/uploads/2025/09/Frame-14.png";
const TI_BANNER       = "https://cdn.steamstatic.com/apps/dota2/images/dpc/social_generic.jpg";
const VCT_BANNER      = "https://cmsassets.rgpub.io/sanity/images/dsfx7636/news_live/aa69698c70f2deddba911d455de42034f522dcdc-1920x1080.png";
const PUBG_BANNER     = "https://wstatic-prod.pubgesports.com/web/live/static/og/img-og-pubg-esports.jpg";
const OWCS_BANNER     = "https://a.storyblok.com/f/267720/1920x1080/00c2df624f/header-owe.png";

// Colour palette
const C_CONVENTION = "#4f9cf9";  // blue
const C_SHOWCASE   = "#b06ff5";  // purple
const C_AWARDS     = "#f5c842";  // gold
const C_ESPORTS    = "#e84855";  // red

export const GAMING_EVENTS: GamingEvent[] = [

  // ── 2025 ──────────────────────────────────────────────────────────────────

  // Awards / showcases that happen early in the year
  {
    id: "dice-2025",
    name: "D.I.C.E. Awards 2025",
    type: "awards",
    startDate: "2025-02-13",
    endDate: "2025-02-13",
    location: "Las Vegas, NV",
    description: "The Academy of Interactive Arts & Sciences' annual awards honoring the best games of the year across 24 categories.",
    url: "https://www.interactive.org",
    color: C_AWARDS,
    logoUrl: DICE_BANNER,
  },
  {
    id: "taipei-game-show-2025",
    name: "Taipei Game Show 2025",
    type: "convention",
    startDate: "2025-01-23",
    endDate: "2025-01-26",
    location: "Taipei, Taiwan",
    description: "Asia's leading gaming expo featuring the latest titles from major publishers and indie developers across the Asia-Pacific region.",
    url: "https://tgs.tca.org.tw/index_e.php",
    color: C_CONVENTION,
    logoUrl: TGS_TW_BANNER,
  },
  {
    id: "gdc-2025",
    name: "GDC 2025",
    type: "convention",
    startDate: "2025-03-17",
    endDate: "2025-03-21",
    location: "San Francisco, CA",
    description: "Game Developers Conference, the world's largest professional game industry event, featuring sessions, summits, and the Independent Games Festival.",
    url: "https://gdconf.com",
    color: C_CONVENTION,
    logoUrl: GDC_BANNER,
  },
  {
    id: "bafta-games-2025",
    name: "BAFTA Games Awards 2025",
    type: "awards",
    startDate: "2025-04-08",
    endDate: "2025-04-08",
    location: "London, UK",
    description: "The British Academy's annual ceremony honouring the best in interactive entertainment — one of the most prestigious awards in the global games industry.",
    url: "https://www.bafta.org/awards/games",
    color: C_AWARDS,
    logoUrl: "https://media.bafta.org/m/1fbbf5c9b45c4e3/original/BAFTA_Games_Awards_logo.png",
  },
  {
    id: "mefcc-2025",
    name: "Middle East Film & Comic Con 2025",
    type: "convention",
    startDate: "2025-04-18",
    endDate: "2025-04-20",
    location: "Abu Dhabi, UAE",
    description: "The Middle East's biggest pop culture convention featuring gaming, cosplay, comics, collectibles, and exclusive reveals.",
    url: "https://www.mefcc.com",
    color: C_CONVENTION,
    logoUrl: MEFCC_BANNER,
  },
  {
    id: "dubai-esports-festival-2025",
    name: "Dubai Esports & Games Festival 2025",
    type: "convention",
    startDate: "2025-04-25",
    endDate: "2025-05-11",
    location: "Dubai, UAE",
    description: "The region's largest gaming festival — 17 days of city-wide gaming events, the GameExpo (May 9–11), tournaments, and activations at Dubai World Trade Centre.",
    url: "https://www.dubaiesportsfestival.com",
    color: C_CONVENTION,
  },
  {
    id: "pax-east-2025",
    name: "PAX East 2025",
    type: "convention",
    startDate: "2025-05-22",
    endDate: "2025-05-25",
    location: "Boston, MA",
    description: "One of the largest gaming conventions in the Eastern United States, bringing together gamers, developers, and publishers.",
    url: "https://east.paxsite.com",
    color: C_CONVENTION,
    logoUrl: PAX_EAST_BANNER,
  },
  {
    id: "summer-game-fest-2025",
    name: "Summer Game Fest 2025",
    type: "showcase",
    startDate: "2025-06-06",
    endDate: "2025-06-09",
    location: "Los Angeles, CA",
    description: "Geoff Keighley's multi-day showcase featuring world premieres, demos, and announcements from major publishers and indie studios.",
    url: "https://www.summergamefest.com",
    color: C_SHOWCASE,
    logoUrl: SGF_BANNER,
  },
  {
    id: "xbox-showcase-2025",
    name: "Xbox Games Showcase 2025",
    type: "showcase",
    startDate: "2025-06-08",
    endDate: "2025-06-08",
    description: "Microsoft's annual showcase revealing upcoming Xbox and PC games, Game Pass additions, and hardware announcements.",
    color: C_SHOWCASE,
    logoUrl: XBOX_SCH_BANNER,
  },
  {
    id: "sdcc-2025",
    name: "San Diego Comic-Con 2025",
    type: "convention",
    startDate: "2025-07-24",
    endDate: "2025-07-27",
    location: "San Diego, CA",
    description: "The iconic pop culture convention featuring major gaming announcements, panels, and exclusive reveals alongside comics, film, and TV.",
    url: "https://www.comic-con.org",
    color: C_CONVENTION,
    logoUrl: SDCC_BANNER,
  },
  {
    id: "ewc-2025",
    name: "Esports World Cup 2025",
    type: "esports",
    startDate: "2025-07-08",
    endDate: "2025-08-24",
    location: "Riyadh, Saudi Arabia",
    description: "The world's biggest esports event — 25 tournaments across 24 games, $75M+ prize pool, 2,000 elite players from 200 clubs across 100+ countries.",
    url: "https://esportsworldcup.com",
    color: C_ESPORTS,
    logoUrl: EWC_BANNER,
  },
  {
    id: "gamescom-onl-2025",
    name: "Gamescom Opening Night Live 2025",
    type: "showcase",
    startDate: "2025-08-19",
    endDate: "2025-08-19",
    location: "Cologne, Germany",
    description: "Geoff Keighley's annual gaming showcase kicking off Gamescom week with world premieres and major announcements broadcast globally.",
    url: "https://www.gamescom.global/en/program/onl",
    color: C_SHOWCASE,
    logoUrl: ONL_BANNER,
  },
  {
    id: "gamescom-2025",
    name: "Gamescom 2025",
    type: "convention",
    startDate: "2025-08-20",
    endDate: "2025-08-24",
    location: "Cologne, Germany",
    description: "The world's largest gaming trade fair with developer showcases, publisher booths, and public expo floors.",
    url: "https://www.gamescom.global",
    color: C_CONVENTION,
    logoUrl: GAMESCOM_BANNER,
  },
  {
    {
    id: "ti-2025",
    name: "The International 2025",
    type: "esports",
    startDate: "2025-09-04",
    endDate: "2025-09-14",
    location: "Hamburg, Germany",
    description: "Dota 2's crown jewel — the world's largest esports prize pool tournament, bringing the top 18 teams together to compete for the Aegis of Champions.",
    url: "https://www.dota2.com/esports/ti",
    color: C_ESPORTS,
    logoUrl: TI_BANNER,
  },
  {
    id: "vct-champions-2025",
    name: "VALORANT Champions 2025",
    type: "esports",
    startDate: "2025-09-12",
    endDate: "2025-10-05",
    location: "Paris, France",
    description: "The VALORANT world championship — 16 elite teams from global VCT leagues compete for the title of best team in the world.",
    url: "https://valorantesports.com",
    color: C_ESPORTS,
    logoUrl: VCT_BANNER,
  },
  {
    id: "chinajoy-2025",
    name: "ChinaJoy 2025",
    type: "convention",
    startDate: "2025-08-01",
    endDate: "2025-08-04",
    location: "Shanghai, China",
    description: "The world's largest digital entertainment expo, showcasing gaming, animation, comics, and online entertainment across Asia.",
    url: "https://en.chinajoy.net",
    color: C_CONVENTION,
  },
  {
    id: "pax-west-2025",
    name: "PAX West 2025",
    type: "convention",
    startDate: "2025-08-29",
    endDate: "2025-09-01",
    location: "Seattle, WA",
    description: "Four days of games, panels, tournaments, and community events on the Pacific Coast.",
    url: "https://west.paxsite.com",
    color: C_CONVENTION,
    logoUrl: PAX_WEST_BANNER,
  },
  {
    id: "tokyo-game-show-2025",
    name: "Tokyo Game Show 2025",
    type: "convention",
    startDate: "2025-09-25",
    endDate: "2025-09-28",
    location: "Chiba, Japan",
    description: "Japan's premier gaming expo where major publishers reveal upcoming titles, with both online and in-person components.",
    url: "https://tgs.cesa.or.jp/english",
    color: C_CONVENTION,
    logoUrl: TGS_BANNER,
  },
  {
    id: "lol-worlds-2025",
    name: "LoL World Championship 2025",
    type: "esports",
    startDate: "2025-10-14",
    endDate: "2025-11-09",
    location: "China (Chengdu & Shanghai)",
    description: "The League of Legends World Championship returns to China — the most-watched annual esports event with hundreds of millions of viewers worldwide.",
    url: "https://lolesports.com",
    color: C_ESPORTS,
  },
  {
    id: "bgs-2025",
    name: "Brasil Game Show 2025",
    type: "convention",
    startDate: "2025-10-09",
    endDate: "2025-10-12",
    location: "São Paulo, Brazil",
    description: "The largest gaming expo in the Americas, bringing together over 300,000 attendees for game announcements, tournaments, and cosplay.",
    url: "https://www.brasilgameshow.com.br",
    color: C_CONVENTION,
    logoUrl: BGS_BANNER,
  },
  {
    id: "pax-aus-2025",
    name: "PAX Aus 2025",
    type: "convention",
    startDate: "2025-10-31",
    endDate: "2025-11-02",
    location: "Melbourne, Australia",
    description: "Australia's biggest gaming convention with three days of gaming, esports, tabletop, and developer panels.",
    url: "https://aus.paxsite.com",
    color: C_CONVENTION,
    logoUrl: PAX_AUS_BANNER,
  },
  {
    id: "igdc-2025",
    name: "India Game Developer Conference 2025",
    type: "convention",
    startDate: "2025-11-05",
    endDate: "2025-11-07",
    location: "Chennai, India",
    description: "India's premier game development conference, connecting developers, publishers, and investors across South Asia.",
    url: "https://indiagdc.com",
    color: C_CONVENTION,
    logoUrl: IGDC_BANNER,
  },
  {
    id: "ffws-2025",
    name: "Free Fire World Series 2025",
    type: "esports",
    startDate: "2025-11-15",
    endDate: "2025-11-16",
    location: "Jakarta, Indonesia",
    description: "The Free Fire global championship — one of the most-watched mobile esports events in Southeast Asia and Latin America, with peak viewership exceeding 5 million.",
    url: "https://ff.garena.com",
    color: C_ESPORTS,
  },
  {
    id: "gstar-2025",
    name: "G-Star 2025",
    type: "convention",
    startDate: "2025-11-13",
    endDate: "2025-11-16",
    location: "Busan, South Korea",
    description: "Korea's largest international game expo, featuring global publishers, indie showcases, and major esports competitions at BEXCO.",
    url: "https://www.gstar.or.kr/eng",
    color: C_CONVENTION,
    logoUrl: GSTAR_BANNER,
  },
  {
    id: "owcs-worlds-2025",
    name: "Overwatch Champions Series World Finals 2025",
    type: "esports",
    startDate: "2025-11-26",
    endDate: "2025-11-30",
    location: "Stockholm, Sweden",
    description: "The OWCS World Finals — top teams from the Americas, EMEA, and Asia-Pacific regions compete for the Overwatch world title.",
    url: "https://overwatchleague.com",
    color: C_ESPORTS,
    logoUrl: OWCS_BANNER,
  },
  {
    id: "golden-joystick-2025",
    name: "Golden Joystick Awards 2025",
    type: "awards",
    startDate: "2025-11-20",
    endDate: "2025-11-20",
    location: "London, UK",
    description: "The world's longest-running public-voted gaming awards, celebrating the best games and creators of the year across 20+ categories.",
    url: "https://www.goldenjoystickawards.com",
    color: C_AWARDS,
    logoUrl: GJA_BANNER,
  },
  {
    id: "pubg-pgc-2025",
    name: "PUBG Global Championship 2025",
    type: "esports",
    startDate: "2025-12-05",
    endDate: "2025-12-14",
    location: "Bangkok, Thailand",
    description: "The PUBG Battle Royale world championship — 32 elite squads from around the globe compete for the season's biggest prize pool.",
    url: "https://pubgesports.com",
    color: C_ESPORTS,
    logoUrl: PUBG_BANNER,
  },
  {
    id: "the-game-awards-2025",
    name: "The Game Awards 2025",
    type: "awards",
    startDate: "2025-12-11",
    endDate: "2025-12-11",
    location: "Los Angeles, CA",
    description: "The gaming industry's biggest night, celebrating the best games of the year with world premiere announcements and live performances.",
    url: "https://thegameawards.com",
    color: C_AWARDS,
    logoUrl: TGA_BANNER,
  },
  {
    id: "games-of-future-2025",
    name: "Games of the Future 2025",
    type: "esports",
    startDate: "2025-12-18",
    endDate: "2025-12-23",
    location: "Abu Dhabi, UAE",
    description: "Phygital sports tournament blending esports and physical disciplines — 850+ participants from 60+ countries across 11 hybrid game formats.",
    url: "https://abudhabi2025.gofuture.games/en",
    color: C_ESPORTS,
  },

  // ── 2026 ──────────────────────────────────────────────────────────────────

  {
    id: "mlbb-m7-2026",
    name: "Mobile Legends M7 World Championship",
    type: "esports",
    startDate: "2026-01-06",
    endDate: "2026-01-25",
    location: "Jakarta, Indonesia",
    description: "The Mobile Legends: Bang Bang World Championship — Southeast Asia's most-watched mobile esports tournament with a massive global following.",
    url: "https://www.mobilelegends.com",
    color: C_ESPORTS,
  },
  {
    id: "taipei-game-show-2026",
    name: "Taipei Game Show 2026",
    type: "convention",
    startDate: "2026-01-29",
    endDate: "2026-02-01",
    location: "Taipei, Taiwan",
    description: "Asia's leading gaming expo featuring the latest titles from major publishers and indie developers across the Asia-Pacific region.",
    url: "https://tgs.tca.org.tw/index_e.php",
    color: C_CONVENTION,
    logoUrl: TGS_TW_BANNER,
  },
  {
    id: "dice-2026",
    name: "D.I.C.E. Awards 2026",
    type: "awards",
    startDate: "2026-02-12",
    endDate: "2026-02-12",
    location: "Las Vegas, NV",
    description: "The Academy of Interactive Arts & Sciences' annual awards honoring the best games of the year across 24 categories.",
    url: "https://www.interactive.org",
    color: C_AWARDS,
    logoUrl: DICE_BANNER,
  },
  {
    id: "gdc-2026",
    name: "GDC 2026",
    type: "convention",
    startDate: "2026-03-16",
    endDate: "2026-03-20",
    location: "San Francisco, CA",
    description: "Game Developers Conference 2026, the professional game industry event featuring sessions, summits, and the Independent Games Festival.",
    url: "https://gdconf.com",
    color: C_CONVENTION,
    logoUrl: GDC_BANNER,
  },
  {
    id: "pax-east-2026",
    name: "PAX East 2026",
    type: "convention",
    startDate: "2026-03-26",
    endDate: "2026-03-29",
    location: "Boston, MA",
    description: "One of the largest gaming conventions in the Eastern US, four days of games, panels, tournaments, and developer showcases.",
    url: "https://east.paxsite.com",
    color: C_CONVENTION,
    logoUrl: PAX_EAST_BANNER,
  },
  {
    id: "bafta-games-2026",
    name: "BAFTA Games Awards 2026",
    type: "awards",
    startDate: "2026-04-17",
    endDate: "2026-04-17",
    location: "London, UK",
    description: "The British Academy's annual ceremony honouring the best in interactive entertainment — one of the most prestigious awards in the global games industry.",
    url: "https://www.bafta.org/awards/games",
    color: C_AWARDS,
    logoUrl: "https://media.bafta.org/m/1fbbf5c9b45c4e3/original/BAFTA_Games_Awards_logo.png",
  },
  {
    id: "dubai-esports-festival-2026",
    name: "Dubai Esports & Games Festival 2026",
    type: "convention",
    startDate: "2026-05-08",
    endDate: "2026-05-24",
    location: "Dubai, UAE",
    description: "The region's largest gaming festival — 17 days of gaming events, GameExpo (May 22–24), tournaments, and activations across Dubai World Trade Centre.",
    url: "https://www.dubaiesportsfestival.com",
    color: C_CONVENTION,
  },
  {
    id: "summer-game-fest-2026",
    name: "Summer Game Fest 2026",
    type: "showcase",
    startDate: "2026-06-05",
    endDate: "2026-06-08",
    location: "Los Angeles, CA",
    description: "Multi-day showcase featuring world premiere announcements and demos from across the industry.",
    url: "https://www.summergamefest.com",
    color: C_SHOWCASE,
    logoUrl: SGF_BANNER,
  },
  {
    id: "sdcc-2026",
    name: "San Diego Comic-Con 2026",
    type: "convention",
    startDate: "2026-07-23",
    endDate: "2026-07-26",
    location: "San Diego, CA",
    description: "Pop culture's biggest annual gathering with major gaming panels and exclusive reveals alongside comics, film, and TV.",
    url: "https://www.comic-con.org",
    color: C_CONVENTION,
    logoUrl: SDCC_BANNER,
  },
  {
    id: "ewc-2026",
    name: "Esports World Cup 2026",
    type: "esports",
    startDate: "2026-07-06",
    endDate: "2026-08-23",
    location: "Riyadh, Saudi Arabia",
    description: "The world's biggest esports event returns to Riyadh — multi-week tournament spanning dozens of titles with hundreds of millions in prize money.",
    url: "https://esportsworldcup.com",
    color: C_ESPORTS,
    logoUrl: EWC_BANNER,
  },
  {
    id: "chinajoy-2026",
    name: "ChinaJoy 2026",
    type: "convention",
    startDate: "2026-07-31",
    endDate: "2026-08-03",
    location: "Shanghai, China",
    description: "The world's largest digital entertainment expo, showcasing gaming, animation, comics, and online entertainment across Asia.",
    url: "https://en.chinajoy.net",
    color: C_CONVENTION,
  },
  {
    id: "gamescom-onl-2026",
    name: "Gamescom Opening Night Live 2026",
    type: "showcase",
    startDate: "2026-08-25",
    endDate: "2026-08-25",
    location: "Cologne, Germany",
    description: "Geoff Keighley's annual gaming showcase kicking off Gamescom week with world premieres and major announcements broadcast globally.",
    url: "https://www.gamescom.global/en/program/onl",
    color: C_SHOWCASE,
    logoUrl: ONL_BANNER,
  },
  {
    id: "gamescom-2026",
    name: "Gamescom 2026",
    type: "convention",
    startDate: "2026-08-26",
    endDate: "2026-08-30",
    location: "Cologne, Germany",
    description: "The world's largest gaming trade fair returns to Cologne with developer showcases and public expo floors.",
    url: "https://www.gamescom.global",
    color: C_CONVENTION,
    logoUrl: GAMESCOM_BANNER,
  },
  {
    id: "mefcc-2026",
    name: "Middle East Film & Comic Con 2026",
    type: "convention",
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    location: "Abu Dhabi, UAE",
    description: "The Middle East's biggest pop culture convention featuring gaming, cosplay, comics, collectibles, and exclusive reveals.",
    url: "https://www.mefcc.com",
    color: C_CONVENTION,
    logoUrl: MEFCC_BANNER,
  },
  {
    id: "bgs-2026",
    name: "Brasil Game Show 2026",
    type: "convention",
    startDate: "2026-10-09",
    endDate: "2026-10-13",
    location: "São Paulo, Brazil",
    description: "The largest gaming expo in the Americas, bringing together over 300,000 attendees for game announcements, tournaments, and cosplay.",
    url: "https://www.brasilgameshow.com.br",
    color: C_CONVENTION,
    logoUrl: BGS_BANNER,
  },
  {
    id: "gstar-2026",
    name: "G-Star 2026",
    type: "convention",
    startDate: "2026-11-19",
    endDate: "2026-11-22",
    location: "Busan, South Korea",
    description: "Korea's largest international game expo, featuring global publishers, indie showcases, and major esports competitions at BEXCO.",
    url: "https://www.gstar.or.kr/eng",
    color: C_CONVENTION,
    logoUrl: GSTAR_BANNER,
  },
  {
    id: "kingdom-of-gaming-2026",
    name: "Kingdom of Gaming 2026",
    type: "convention",
    startDate: "2026-12-01",
    endDate: "2026-12-03",
    location: "Riyadh, Saudi Arabia",
    description: "Saudi Arabia's flagship gaming event debut — 20,000+ visitors, 300 exhibitors, 500 studios and developers, state-backed.",
    url: "https://esportsworldcup.com",
    color: C_CONVENTION,
  },
  {
    id: "the-game-awards-2026",
    name: "The Game Awards 2026",
    type: "awards",
    startDate: "2026-12-10",
    endDate: "2026-12-10",
    location: "Los Angeles, CA",
    description: "The gaming industry's biggest night, celebrating the best games of the year.",
    url: "https://thegameawards.com",
    color: C_AWARDS,
    logoUrl: TGA_BANNER,
  },
];

export function getEventsForDate(dateStr: string): GamingEvent[] {
  const date = new Date(dateStr + "T12:00:00");
  return GAMING_EVENTS.filter((e) => {
    const start = new Date(e.startDate + "T12:00:00");
    const end   = new Date(e.endDate   + "T12:00:00");
    return date >= start && date <= end;
  });
}
