import type { GameRelease } from "./releases";

// Fallback releases used when Dashboard and RAWG are unavailable.
// All dates sourced directly from the dashboard's gaming_trends.json (IGDB data).
// Only includes games with meaningful community interest (hypes >= 25 in IGDB).
export const HARDCODED_RELEASES: GameRelease[] = [

  // ── 2026 ──────────────────────────────────────────────────────────────────
  {
    id: 900001,
    name: "Crimson Desert",
    slug: "crimson-desert",
    released: "2026-03-19",
    background_image: null,
    platforms: ["PS5", "PC", "Mac", "Xbox Series"],
    genres: ["Action", "RPG", "Open World"],
  },
  {
    id: 900002,
    name: "Screamer",
    slug: "screamer--1",
    released: "2026-03-26",
    background_image: null,
    platforms: ["PS5", "Xbox Series", "PC"],
    genres: ["Action"],
  },
  {
    id: 900003,
    name: "Darwin's Paradox",
    slug: "darwins-paradox",
    released: "2026-04-02",
    background_image: null,
    platforms: ["PC", "Switch 2", "PS5", "Xbox Series"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900004,
    name: "Replaced",
    slug: "replaced",
    released: "2026-04-14",
    background_image: null,
    platforms: ["Xbox One", "PC", "Xbox Series"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900005,
    name: "Mouse: P.I. For Hire",
    slug: "mouse-pi-for-hire--1",
    released: "2026-04-16",
    background_image: null,
    platforms: ["Xbox Series", "Switch", "PS5", "Switch 2", "PC"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900006,
    name: "Pragmata",
    slug: "pragmata",
    released: "2026-04-17",
    background_image: null,
    platforms: ["Switch 2", "PS5", "PC", "Xbox Series"],
    genres: ["Action", "Adventure", "Sci-Fi"],
  },
  {
    id: 900007,
    name: "Tides of Tomorrow",
    slug: "tides-of-tomorrow",
    released: "2026-04-22",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Strategy"],
  },
  {
    id: 900008,
    name: "Outbound",
    slug: "outbound",
    released: "2026-04-23",
    background_image: null,
    platforms: ["Switch 2", "Switch", "PC", "PS5", "Xbox Series"],
    genres: ["Adventure", "Co-op"],
  },
  {
    id: 900009,
    name: "Saros",
    slug: "saros",
    released: "2026-04-30",
    background_image: null,
    platforms: ["PS5"],
    genres: ["Action", "RPG"],
  },
  {
    id: 900010,
    name: "Mixtape",
    slug: "mixtape--1",
    released: "2026-05-07",
    background_image: null,
    platforms: ["PC", "Xbox Series", "PS5", "Switch 2"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900011,
    name: "Forza Horizon 6",
    slug: "forza-horizon-6",
    released: "2026-05-19",
    background_image: null,
    platforms: ["PC", "Xbox Series"],
    genres: ["Racing", "Open World"],
  },
  {
    id: 900014,
    name: "Doom: The Dark Ages",
    slug: "doom-the-dark-ages",
    released: "2026-05-15",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Shooter"],
  },
{
    id: 900012,
    name: "Deadlock",
    slug: "deadlock",
    released: "2026-08-15",
    background_image: null,
    platforms: ["PC"],
    genres: ["Shooter", "MOBA"],
  },
  {
    id: 900013,
    name: "GTA VI",
    slug: "grand-theft-auto-vi",
    released: "2026-11-01",
    background_image: null,
    platforms: ["PS5", "Xbox Series"],
    genres: ["Action", "Open World"],
  },
];
