import type { GameRelease } from "./releases";

// Curated game releases. 2025 entries are kept for historical navigation.
// 2026 entries reflect announced titles as of the August 2025 knowledge cutoff.
// RAWG API data (when RAWG_API_KEY is set) will override and supplement these.
export const HARDCODED_RELEASES: GameRelease[] = [

  // ── 2026 (upcoming from March 2026) ────────────────────────────────────────
  {
    id: 900019,
    name: "Ghost of Yotei",
    slug: "ghost-of-yotei",
    released: "2026-04-02",
    background_image: null,
    platforms: ["PS5"],
    genres: ["Action", "Adventure", "Open World"],
  },
  {
    id: 900018,
    name: "Metroid Prime 4: Beyond",
    slug: "metroid-prime-4-beyond",
    released: "2026-04-14",
    background_image: null,
    platforms: ["Switch"],
    genres: ["Action", "Adventure", "FPS"],
  },
  {
    id: 900020,
    name: "GTA VI",
    slug: "grand-theft-auto-vi",
    released: "2026-05-26",
    background_image: null,
    platforms: ["PS5", "Xbox Series"],
    genres: ["Action", "Open World"],
  },
  {
    id: 900021,
    name: "The Witcher 4",
    slug: "the-witcher-4",
    released: "2026-07-01",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["RPG", "Action", "Open World"],
  },
  {
    id: 900022,
    name: "Intergalactic: The Heretic Prophet",
    slug: "intergalactic-the-heretic-prophet",
    released: "2026-09-01",
    background_image: null,
    platforms: ["PS5"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900023,
    name: "Fable",
    slug: "fable-2024",
    released: "2026-08-01",
    background_image: null,
    platforms: ["PC", "Xbox Series"],
    genres: ["RPG", "Action", "Open World"],
  },
  {
    id: 900024,
    name: "Hollow Knight: Silksong",
    slug: "hollow-knight-silksong",
    released: "2026-06-01",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series", "Switch"],
    genres: ["Action", "Platformer", "Metroidvania"],
  },

  // ── 2025 (historical — navigate back to browse) ────────────────────────────
  {
    id: 900001,
    name: "Avowed",
    slug: "avowed",
    released: "2025-02-18",
    background_image: null,
    platforms: ["PC", "Xbox Series"],
    genres: ["RPG", "Action"],
  },
  {
    id: 900002,
    name: "Monster Hunter Wilds",
    slug: "monster-hunter-wilds",
    released: "2025-02-28",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "RPG"],
  },
  {
    id: 900003,
    name: "Split Fiction",
    slug: "split-fiction",
    released: "2025-03-06",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Adventure", "Co-op"],
  },
  {
    id: 900004,
    name: "Assassin's Creed Shadows",
    slug: "assassins-creed-shadows",
    released: "2025-03-20",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Adventure", "Stealth"],
  },
  {
    id: 900005,
    name: "South of Midnight",
    slug: "south-of-midnight",
    released: "2025-04-08",
    background_image: null,
    platforms: ["PC", "Xbox Series"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900006,
    name: "Clair Obscur: Expedition 33",
    slug: "clair-obscur-expedition-33",
    released: "2025-04-24",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["RPG", "Turn-Based"],
  },
  {
    id: 900007,
    name: "DOOM: The Dark Ages",
    slug: "doom-the-dark-ages",
    released: "2025-05-15",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "FPS"],
  },
  {
    id: 900008,
    name: "Elden Ring: Nightreign",
    slug: "elden-ring-nightreign",
    released: "2025-05-30",
    background_image: null,
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series"],
    genres: ["Action", "RPG", "Co-op"],
  },
  {
    id: 900009,
    name: "Death Stranding 2: On the Beach",
    slug: "death-stranding-2-on-the-beach",
    released: "2025-06-26",
    background_image: null,
    platforms: ["PS5"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900010,
    name: "Mafia: The Old Country",
    slug: "mafia-the-old-country",
    released: "2025-08-08",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900011,
    name: "Borderlands 4",
    slug: "borderlands-4",
    released: "2025-09-23",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Shooter", "RPG"],
  },
];
