import type { GameRelease } from "./releases";

// Well-known game releases to supplement RAWG API data
export const HARDCODED_RELEASES: GameRelease[] = [
  {
    id: 900001,
    name: "Avowed",
    slug: "avowed",
    released: "2025-02-18",
    background_image: "https://media.rawg.io/media/games/157/15742b55827b7e4ed1780f8e56c07002.jpg",
    platforms: ["PC", "Xbox Series"],
    genres: ["RPG", "Action"],
  },
  {
    id: 900002,
    name: "Monster Hunter Wilds",
    slug: "monster-hunter-wilds",
    released: "2025-02-28",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "RPG"],
  },
  {
    id: 900003,
    name: "Split Fiction",
    slug: "split-fiction",
    released: "2025-03-06",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Adventure", "Co-op"],
  },
  {
    id: 900004,
    name: "Assassin's Creed Shadows",
    slug: "assassins-creed-shadows",
    released: "2025-03-20",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Adventure", "Stealth"],
  },
  {
    id: 900005,
    name: "South of Midnight",
    slug: "south-of-midnight",
    released: "2025-04-08",
    background_image: null,
    platforms: ["PC", "Xbox Series"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900006,
    name: "Clair Obscur: Expedition 33",
    slug: "clair-obscur-expedition-33",
    released: "2025-04-24",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["RPG", "Turn-Based"],
  },
  {
    id: 900007,
    name: "DOOM: The Dark Ages",
    slug: "doom-the-dark-ages",
    released: "2025-05-15",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "FPS"],
  },
  {
    id: 900008,
    name: "Elden Ring: Nightreign",
    slug: "elden-ring-nightreign",
    released: "2025-05-30",
    background_image: null,
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series"],
    genres: ["Action", "RPG", "Co-op"],
  },
  {
    id: 900009,
    name: "Death Stranding 2: On the Beach",
    slug: "death-stranding-2-on-the-beach",
    released: "2025-06-26",
    background_image: null,
    platforms: ["PS5"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900010,
    name: "Mafia: The Old Country",
    slug: "mafia-the-old-country",
    released: "2025-08-08",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Adventure"],
  },
  {
    id: 900011,
    name: "Borderlands 4",
    slug: "borderlands-4",
    released: "2025-09-23",
    background_image: null,
    platforms: ["PC", "PS5", "Xbox Series"],
    genres: ["Action", "Shooter", "RPG"],
  },
];
